### ISSUE TITLE
Post to internal slack if nightly tests fail

### ISSUE THREAD

**Issue by praateekmahajan** [NVIDIA/NeMo-Curator#488]
**Is your feature request related to a problem? Please describe.**
If nightly scheduled tests fail then we would like to be notified on slack.
**Describe the solution you'd like**
 Code as follows could work however we'd have to figure out the slack auth tokens
```
      - name: Notify on failure
        if: failure() && github.event_name == 'schedule'
        uses: slackapi/slack-github-action@v1
        with:
          channel-id: 'xyz'
          slack-message: "Nightly GPU tests failed! Check: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }} # add secret somewhere

``` 
**Describe alternatives you've considered**

**Additional context**
